# Generated by Django 5.1.4 on 2024-12-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('recipename', models.CharField(max_length=50)),
                ('recipe', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
    ]
