# Generated by Django 5.1.4 on 2024-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ingredient_recipe_restaurant_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='nutrients',
            new_name='calories',
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.TextField(blank=True, null=True),
        ),
    ]
