# Generated by Django 5.1.4 on 2024-12-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_nutrients_recipe_calories_recipe_carbohydrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
